/**
 * Generates src/data/us-map.ts: simplified SVG paths for every state, keyed by postal code.
 *
 *   node scripts/make-us-map.mjs
 *
 * Source: us-atlas states-albers-10m.json (U.S. Census Bureau cartographic boundaries, public
 * domain), already projected with d3.geoAlbersUsa().scale(1300).translate([487.5, 305]) into a
 * 975×610 frame with Alaska and Hawaii as insets. FootprintMap.astro projects project pins with
 * the same projection, so the shapes and the pins line up exactly.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { feature } from 'topojson-client';
import { presimplify, simplify, quantile } from 'topojson-simplify';
import { geoPath } from 'd3-geo';

const require = createRequire(import.meta.url);
const topology = JSON.parse(
  readFileSync(require.resolve('us-atlas/states-albers-10m.json'), 'utf8'),
);

// Keep the most significant points only: borders stay recognisable at map size and the
// output stays small enough to inline in the page.
const KEEP = Number(process.env.KEEP ?? 0.07);
const pre = presimplify(topology);
const simplified = simplify(pre, quantile(pre, KEEP));
const area = geoPath().area;

/** Drop islands smaller than `min` square pixels; they are invisible at map size. */
function dropSpecks(f, min = 1.5) {
  const g = f.geometry;
  if (g?.type !== 'MultiPolygon') return f;
  const polys = g.coordinates.filter(
    (rings) => area({ type: 'Polygon', coordinates: rings }) >= min,
  );
  return { ...f, geometry: { type: 'MultiPolygon', coordinates: polys } };
}

const states = feature(simplified, simplified.objects.states).features.map((f) => dropSpecks(f));

const POSTAL = {
  Alabama: 'AL',
  Alaska: 'AK',
  Arizona: 'AZ',
  Arkansas: 'AR',
  California: 'CA',
  Colorado: 'CO',
  Connecticut: 'CT',
  Delaware: 'DE',
  'District of Columbia': 'DC',
  Florida: 'FL',
  Georgia: 'GA',
  Hawaii: 'HI',
  Idaho: 'ID',
  Illinois: 'IL',
  Indiana: 'IN',
  Iowa: 'IA',
  Kansas: 'KS',
  Kentucky: 'KY',
  Louisiana: 'LA',
  Maine: 'ME',
  Maryland: 'MD',
  Massachusetts: 'MA',
  Michigan: 'MI',
  Minnesota: 'MN',
  Mississippi: 'MS',
  Missouri: 'MO',
  Montana: 'MT',
  Nebraska: 'NE',
  Nevada: 'NV',
  'New Hampshire': 'NH',
  'New Jersey': 'NJ',
  'New Mexico': 'NM',
  'New York': 'NY',
  'North Carolina': 'NC',
  'North Dakota': 'ND',
  Ohio: 'OH',
  Oklahoma: 'OK',
  Oregon: 'OR',
  Pennsylvania: 'PA',
  'Rhode Island': 'RI',
  'South Carolina': 'SC',
  'South Dakota': 'SD',
  Tennessee: 'TN',
  Texas: 'TX',
  Utah: 'UT',
  Vermont: 'VT',
  Virginia: 'VA',
  Washington: 'WA',
  'West Virginia': 'WV',
  Wisconsin: 'WI',
  Wyoming: 'WY',
};

const path = geoPath().digits(1);
const rows = states
  .map((f) => ({ id: POSTAL[f.properties.name], name: f.properties.name, d: path(f) }))
  .filter((s) => s.id && s.d)
  .sort((a, b) => a.id.localeCompare(b.id));

const missing = Object.values(POSTAL).filter((id) => !rows.some((r) => r.id === id));
if (missing.length) throw new Error(`States missing from the atlas: ${missing.join(', ')}`);

const out = `/**
 * Generated by scripts/make-us-map.mjs; do not edit by hand.
 * U.S. state outlines (Census Bureau cartographic boundaries via us-atlas, public domain),
 * projected with d3.geoAlbersUsa().scale(1300).translate([487.5, 305]), Alaska and Hawaii inset.
 */
export const US_MAP = {
  width: 975,
  height: 610,
  scale: 1300,
  translate: [487.5, 305] as [number, number],
};

export interface StateShape {
  /** Postal code, e.g. "NC". */
  id: string;
  name: string;
  d: string;
}

export const US_STATES: StateShape[] = ${JSON.stringify(rows, null, 2)};
`;

writeFileSync('src/data/us-map.ts', out);
const bytes = rows.reduce((n, r) => n + r.d.length, 0);
console.log(
  `Wrote src/data/us-map.ts: ${rows.length} states, ${(bytes / 1024).toFixed(1)} KB of path data`,
);
